package com.xamthien.model;
// Generated Jul 15, 2018 1:36:57 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TacGia generated by hbm2java
 */
@Entity
@Table(name = "TAC_GIA", catalog = "less1")
public class TacGia implements java.io.Serializable {

	private Integer id;
	private String name;
	private String phone;
	private Set<Sach> saches = new HashSet<Sach>(0);

	public TacGia() {
	}

	public TacGia(String name, String phone) {
		this.name = name;
		this.phone = phone;
	}

	public TacGia(String name, String phone, Set<Sach> saches) {
		this.name = name;
		this.phone = phone;
		this.saches = saches;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PHONE", nullable = false, length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tacGia")
	public Set<Sach> getSaches() {
		return this.saches;
	}

	public void setSaches(Set<Sach> saches) {
		this.saches = saches;
	}

}
