package com.xamthien.model;
// Generated Jul 21, 2018 4:02:18 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FlightSchedules generated by hbm2java
 */
@Entity
@Table(name = "flight_schedules", catalog = "ebflight")
public class FlightSchedules implements java.io.Serializable {

	private Integer fid;
	private Airline airline;
	private String FFrom;
	private String FTo;
	private int arrivalTime;
	private Date departureTime;
	private String ortherDetails;
	private Set<Reservation> reservations = new HashSet<Reservation>(0);

	public FlightSchedules() {
	}

	public FlightSchedules(Airline airline, String FFrom, String FTo, int arrivalTime, Date departureTime) {
		this.airline = airline;
		this.FFrom = FFrom;
		this.FTo = FTo;
		this.arrivalTime = arrivalTime;
		this.departureTime = departureTime;
	}

	public FlightSchedules(Airline airline, String FFrom, String FTo, int arrivalTime, Date departureTime,
			String ortherDetails, Set<Reservation> reservations) {
		this.airline = airline;
		this.FFrom = FFrom;
		this.FTo = FTo;
		this.arrivalTime = arrivalTime;
		this.departureTime = departureTime;
		this.ortherDetails = ortherDetails;
		this.reservations = reservations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "FID", unique = true, nullable = false)
	public Integer getFid() {
		return this.fid;
	}

	public void setFid(Integer fid) {
		this.fid = fid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AIRLINE_CODE", nullable = false)
	public Airline getAirline() {
		return this.airline;
	}

	public void setAirline(Airline airline) {
		this.airline = airline;
	}

	@Column(name = "F_FROM", nullable = false, length = 100)
	public String getFFrom() {
		return this.FFrom;
	}

	public void setFFrom(String FFrom) {
		this.FFrom = FFrom;
	}

	@Column(name = "F_TO", nullable = false, length = 100)
	public String getFTo() {
		return this.FTo;
	}

	public void setFTo(String FTo) {
		this.FTo = FTo;
	}

	@Column(name = "ARRIVAL_TIME", nullable = false)
	public int getArrivalTime() {
		return this.arrivalTime;
	}

	public void setArrivalTime(int arrivalTime) {
		this.arrivalTime = arrivalTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DEPARTURE_TIME", nullable = false, length = 19)
	public Date getDepartureTime() {
		return this.departureTime;
	}

	public void setDepartureTime(Date departureTime) {
		this.departureTime = departureTime;
	}

	@Column(name = "ORTHER_DETAILS")
	public String getOrtherDetails() {
		return this.ortherDetails;
	}

	public void setOrtherDetails(String ortherDetails) {
		this.ortherDetails = ortherDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flightSchedules")
	public Set<Reservation> getReservations() {
		return this.reservations;
	}

	public void setReservations(Set<Reservation> reservations) {
		this.reservations = reservations;
	}

}
