package com.xamthien.model;
// Generated Jul 21, 2018 4:02:18 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PaymnetMethod generated by hbm2java
 */
@Entity
@Table(name = "paymnet_method", catalog = "ebflight")
public class PaymnetMethod implements java.io.Serializable {

	private Integer pid;
	private String PName;
	private Set<Reservation> reservations = new HashSet<Reservation>(0);

	public PaymnetMethod() {
	}

	public PaymnetMethod(String PName) {
		this.PName = PName;
	}

	public PaymnetMethod(String PName, Set<Reservation> reservations) {
		this.PName = PName;
		this.reservations = reservations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PID", unique = true, nullable = false)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@Column(name = "P_NAME", nullable = false, length = 50)
	public String getPName() {
		return this.PName;
	}

	public void setPName(String PName) {
		this.PName = PName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paymnetMethod")
	public Set<Reservation> getReservations() {
		return this.reservations;
	}

	public void setReservations(Set<Reservation> reservations) {
		this.reservations = reservations;
	}

}
