package com.xamthien.model;
// Generated Jul 23, 2018 3:57:16 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reservation generated by hbm2java
 */
@Entity
@Table(name = "RESERVATION", catalog = "ebflight")
public class Reservation implements java.io.Serializable {

	private Integer rid;
	private Customer customer;
	private FlightSchedules flightSchedules;
	private PaymnetMethod paymnetMethod;
	private ReservationStatus reservationStatus;
	private Date dateOfReservation;

	public Reservation() {
	}

	public Reservation(Customer customer, FlightSchedules flightSchedules, PaymnetMethod paymnetMethod,
			ReservationStatus reservationStatus, Date dateOfReservation) {
		this.customer = customer;
		this.flightSchedules = flightSchedules;
		this.paymnetMethod = paymnetMethod;
		this.reservationStatus = reservationStatus;
		this.dateOfReservation = dateOfReservation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "RID", unique = true, nullable = false)
	public Integer getRid() {
		return this.rid;
	}

	public void setRid(Integer rid) {
		this.rid = rid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CID", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FID", nullable = false)
	public FlightSchedules getFlightSchedules() {
		return this.flightSchedules;
	}

	public void setFlightSchedules(FlightSchedules flightSchedules) {
		this.flightSchedules = flightSchedules;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PID", nullable = false)
	public PaymnetMethod getPaymnetMethod() {
		return this.paymnetMethod;
	}

	public void setPaymnetMethod(PaymnetMethod paymnetMethod) {
		this.paymnetMethod = paymnetMethod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RSID", nullable = false)
	public ReservationStatus getReservationStatus() {
		return this.reservationStatus;
	}

	public void setReservationStatus(ReservationStatus reservationStatus) {
		this.reservationStatus = reservationStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_OF_RESERVATION", nullable = false, length = 19)
	public Date getDateOfReservation() {
		return this.dateOfReservation;
	}

	public void setDateOfReservation(Date dateOfReservation) {
		this.dateOfReservation = dateOfReservation;
	}

}
