package com.xamthien.model;
// Generated Jul 23, 2018 3:57:16 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ReservationStatus generated by hbm2java
 */
@Entity
@Table(name = "RESERVATION_STATUS", catalog = "ebflight")
public class ReservationStatus implements java.io.Serializable {

	private Integer rsid;
	private String rsName;
	private Set<Reservation> reservations = new HashSet<Reservation>(0);

	public ReservationStatus() {
	}

	public ReservationStatus(String rsName) {
		this.rsName = rsName;
	}

	public ReservationStatus(String rsName, Set<Reservation> reservations) {
		this.rsName = rsName;
		this.reservations = reservations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "RSID", unique = true, nullable = false)
	public Integer getRsid() {
		return this.rsid;
	}

	public void setRsid(Integer rsid) {
		this.rsid = rsid;
	}

	@Column(name = "RS_NAME", nullable = false, length = 50)
	public String getRsName() {
		return this.rsName;
	}

	public void setRsName(String rsName) {
		this.rsName = rsName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reservationStatus")
	public Set<Reservation> getReservations() {
		return this.reservations;
	}

	public void setReservations(Set<Reservation> reservations) {
		this.reservations = reservations;
	}

}
