package com.xamthien.model;
// Generated Jul 23, 2018 3:57:16 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "ROLE", catalog = "ebflight")
public class Role implements java.io.Serializable {

	private Integer rid;
	private String RName;
	private Set<AppUser> users = new HashSet<AppUser>(0);

	public Role() {
	}

	public Role(String RName) {
		this.RName = RName;
	}

	public Role(String RName, Set<AppUser> users) {
		this.RName = RName;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "RID", unique = true, nullable = false)
	public Integer getRid() {
		return this.rid;
	}

	public void setRid(Integer rid) {
		this.rid = rid;
	}

	@Column(name = "R_NAME", nullable = false, length = 20)
	public String getRName() {
		return this.RName;
	}

	public void setRName(String RName) {
		this.RName = RName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<AppUser> getUsers() {
		return this.users;
	}

	public void setUsers(Set<AppUser> users) {
		this.users = users;
	}

}
