package com.xamthien.model;
// Generated Jul 18, 2018 3:55:07 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AppUser generated by hbm2java
 */
@Entity
@Table(name = "APP_USER", catalog = "springsecurity", uniqueConstraints = @UniqueConstraint(columnNames = "USER_NAME"))
public class AppUser implements java.io.Serializable {

	private long userId;
	private String userName;
	private String encrytedPassword;
	private boolean enabled;
	private Set<UserRole> userRoles = new HashSet<UserRole>(0);

	public AppUser() {
	}

	public AppUser(long userId, String userName, String encrytedPassword, boolean enabled) {
		this.userId = userId;
		this.userName = userName;
		this.encrytedPassword = encrytedPassword;
		this.enabled = enabled;
	}

	public AppUser(long userId, String userName, String encrytedPassword, boolean enabled, Set<UserRole> userRoles) {
		this.userId = userId;
		this.userName = userName;
		this.encrytedPassword = encrytedPassword;
		this.enabled = enabled;
		this.userRoles = userRoles;
	}

	@Id

	@Column(name = "USER_ID", unique = true, nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Column(name = "USER_NAME", unique = true, nullable = false, length = 36)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "ENCRYTED_PASSWORD", nullable = false, length = 128)
	public String getEncrytedPassword() {
		return this.encrytedPassword;
	}

	public void setEncrytedPassword(String encrytedPassword) {
		this.encrytedPassword = encrytedPassword;
	}

	@Column(name = "ENABLED", nullable = false)
	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appUser")
	public Set<UserRole> getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set<UserRole> userRoles) {
		this.userRoles = userRoles;
	}

}
